#!/bin/bash
echo $(echo "obase=8" | cat - <(echo "ibase=5" && echo "$WATER" | tr 'water' '01234' | xargs) <(echo "ibase=4" && echo "$STIR" | tr 'stir' '0123' | xargs) | bc) | tr '01234567' 'bestchol'
